module Schemable
  class AttributeSchemaGenerator
    attr_reader model: Class
    attr_reader model_definition: Definition
    attr_reader configuration: Configuration
    attr_reader response: Hash[Symbol, any]?
    attr_reader schema_modifier: SchemaModifier

    def initialize: (Definition) -> void
    def generate: -> (Hash[Symbol, any] | Array[any])
    def generate_attribute_schema: (Symbol) -> Hash[Symbol, any]
  end
end
