module Schemable
  class Configuration
    attr_accessor orm: Symbol
    attr_accessor float_as_string: bool
    attr_accessor decimal_as_string: bool
    attr_accessor pagination_enabled: bool
    attr_accessor use_serialized_instance: bool
    attr_accessor custom_defined_enum_method: Symbol?
    attr_accessor enum_prefix_for_simple_enum: String?
    attr_accessor enum_suffix_for_simple_enum: String?
    attr_accessor custom_type_mappers: Hash[Symbol, any]
    attr_accessor infer_attributes_from_custom_method: Symbol?
    attr_accessor custom_meta_response_schema: Hash[Symbol, any]?
    attr_accessor infer_attributes_from_jsonapi_serializable: bool


    def initialize: -> void
    def type_mapper: (Symbol) -> Hash[Symbol, any]
    def add_custom_type_mapper: (Symbol, Hash[Symbol, any]) -> void
  end
end
