module Schemable
  class RelationshipSchemaGenerator
    attr_accessor model_definition: Definition
    attr_accessor schema_modifier: SchemaModifier
    attr_accessor relationships: Hash[Symbol, any]

    def initialize: (Definition) -> void

    def generate: (?relationships_to_exclude_from_expansion: Array[String], ?expand: bool) -> (Hash[Symbol, any] | Array[Hash[Symbol, any]])

    def generate_schema: (String, ?collection: bool) -> Hash[Symbol, any]
  end
end
