module Schemable
  class ResponseSchemaGenerator
    attr_reader model: Class
    attr_reader model_definition: Definition
    attr_reader schema_modifier: SchemaModifier

    def initialize: (Definition) -> void
    def meta: -> Hash[Symbol, any]
    def jsonapi: -> Hash[Symbol, any]
    def generate: (expand: bool, relationships_to_exclude_from_expansion: Array[Symbol], collection: bool) -> Hash[Symbol, any]
  end
end
