module Schemable
  VERSION: String
  def generate_schemas: () -> Array[Hash[Symbol, Hash[Symbol, any]]]
  def configure: () { (Configuration) -> Configuration } -> Configuration
  attr_accessor configuration: Configuration
end
